### ISSUE TITLE
What is the default admin key?

### ISSUE THREAD

**Issue by tho068** [jderuiter/javacard-openpgpcard#4] opened 2017-07-21 15:46 UTC

**Comment by tho068** [comment] 2017-07-21 15:52
It is not working with 12345678 which usually is the default admin key. The card key 123456 however, works fine.

**Comment by jderuiter** [comment] 2017-08-07 12:06
Looking at the code it should be 12345678. Could you provide the commands you tried that failed?

**Comment by hexum** [comment] 2017-11-22 22:24
In my case only 12345678 is being accepted on setting name.
I see no problems for now.

Version under tests: cada19e

**Comment by jderuiter** [comment] 2017-11-30 15:52
The default admin key 12345678 works for me so I'm closing this issue. If you are still experiencing issues with this feel free to open a new issue with a detailed explanation to reproduce it.

**Closed as completed by jderuiter** 2017-11-30 15:52 UTC
